POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Algum serviço2",
    "description": "testes",
    "price": 1250,
    "image": "https://unsplash.com/photos/Juq7T-frQs8"
}

###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/63bef14686f07f3a48d5076e

###
DELETE http://localhost:3000/api/services/63bef14686f07f3a48d5076e